name: Setup Compiler Cache

on:
  workflow_call:

jobs:
  ccache:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare compiler cache
        id: prep-ccache
        shell: bash
        run: |
          mkdir -p "${CCACHE_DIR:-$HOME/.ccache}"
          echo "dir=${CCACHE_DIR:-$HOME/.ccache}" >> $GITHUB_OUTPUT
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT

      - name: Setup compiler cache
        id: cache-ccache
        uses: actions/cache@5a3ec84eff66
