[workspace]
name = "scipy-ci"
description = "Environment and task management for SciPy CI"
authors = ["SciPy Developers <scipy-dev@python.org>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]


### Environments ###

[environments.build]
features = ["build-deps", "build-task"]
solve-group = "default"

[environments.test]
features = ["build-deps", "test-deps", "test-task"]
solve-group = "default"

[environments.lint]
features = ["lint"]

[environments.cupy]
features = ["build-deps", "test-deps", "cupy"]

[environments.torch-cuda]
features = ["build-deps", "test-deps", "cuda", "mkl", "torch-cuda"]
solve-group = "cuda12"

[environments.jax-cuda]
features = ["build-deps", "test-deps", "cuda", "mkl", "jax-cuda"]
solve-group = "cuda12"

[environments.array-api-cpu]
features = ["build-deps", "test-deps", "cpu", "mkl", "array_api_strict", "dask", "jax-cpu", "torch-cpu"]


### Default dependencies (included in all environments) ###

[dependencies]
spin = "*"


### Default building ###

[feature.build-deps.dependencies]
compilers = "*"
pkg-config = "*"
ninja = "*"
meson = "*"
meson-python = "*"
cython = "*"
python-build = "*"
pip = "*"
blas-devel = "*"
numpy = "*"
pybind11 = "*"
pythran = "*"

[feature.build-task.tasks.build]
cmd = "spin build --setup-args=-Dblas=blas --setup-args=-Dlapack=lapack --setup-args=-Duse-g77-abi=true"
cwd = "../.."
env = { CC = "ccache $CC", CXX = "ccache $CXX", FC = "ccache $FC" }
description = "Build SciPy (default settings)"


### Default testing ###

[feature.test-deps.dependencies]
pytest = "*"
hypothesis = "*"
pytest-cov = "*"
pytest-timeout = "*"
pytest-xdist = "*"
threadpoolctl = "*"
pooch = "*"
mpmath = "*"
gmpy2 = "*"
ccache = "*"
marray-python = "*"

[feature.test-task.tasks.test]
cmd = "spin test --no-build"
cwd = "../.."
depends-on = "build"
description = "Test SciPy (default settings)"


### Linting ###

[feature.lint]
platforms = ["linux-64", "osx-arm64", "win-64"]

[feature.lint.dependencies]
ruff = "*"
cython-lint = "*"
packaging = "*"

[feature.lint.tasks.lint]
cmd = "spin lint"
cwd = "../.."
description = "Run main lint checks"

[feature.lint.tasks.check-python-h]
cmd = "python check_python_h_first.py"
cwd = "../../tools"
description = "Check that `Python.h` is included before any stdlib headers"


### BLAS/LAPACK features ###

[feature.mkl.target.linux-64.dependencies]
libblas = { version = "*", build = "*mkl" }
mkl = "*"

[feature.mkl.tasks.build-mkl]
cmd = "spin build --build-dir=build-mkl --setup-args=-Dblas=mkl-dynamic-ilp64-seq --setup-args=-Duse-g77-abi=true"
cwd = "scipy"
env = { CC = "ccache $CC", CXX = "ccache $CXX", FC = "ccache $FC" }
description = "Build with MKL BLAS"


# [feature.accelerate]
# platforms = ["osx-arm64"]

# [feature.accelerate.dependencies]
# libblas = { version = ">=3.9.0,<4", build = "*accelerate" }

# [feature.accelerate-lp64.tasks.build-accelerate]
# cmd = "spin build --build-dir=build-accelerate --with-accelerate"
# cwd = "../.."
# env = { CC = "ccache $CC", CXX = "ccache $CXX", FC = "ccache $FC" }

# [feature.accelerate-ilp64.tasks.build-accelerate]
# cmd = "spin build --build-dir=build-accelerate -S-Dblas=accelerate -S-Duse-ilp64=true -S-Dblas-symbol-suffix='$NEWLAPACK$ILP64'"
# cwd = "../.."
# env = { CC = "ccache $CC", CXX = "ccache $CXX", FC = "ccache $FC" }

# [feature.accelerate.tasks.test-accelerate-full]
# cmd = "spin test --no-build --build-dir=build-accelerate -m full"
# cwd = "../.."
# depends-on = "build-accelerate"


### CPU/CUDA features ###

[feature.cpu]
platforms = ["linux-64", "osx-arm64", "win-64"]

[feature.cpu.tasks.test-cpu]
cmd = "spin test --no-build -b all -m 'array_api_backends and not slow'"
cwd = "../.."
depends-on = "build"
description = "Test with all CPU array backends"


[feature.cuda]
platforms = ["linux-64"]
# XXX: JAX needs cuda 12 right now, CuPy seems to need cuda 13
# so this feature is not included in the CuPy environment
system-requirements = { cuda = "12" }

[feature.cuda.dependencies]
cuda-version = "12.*"

[feature.cuda.tasks.test-cuda]
cmd = "spin test --no-build -b cupy -b torch -b jax.numpy -m 'array_api_backends and not slow'"
cwd = "../.."
env.SCIPY_DEVICE = "cuda"
depends-on = "build"
description = "Test with all CUDA array backends"


### Array libraries ###

[feature.torch-cpu]
platforms = ["linux-64", "osx-arm64", "win-64"]

[feature.torch-cpu.dependencies]
pytorch-cpu = "*"

[feature.torch-cpu.tasks.test-torch]
cmd = "spin test --no-build -b torch -m 'array_api_backends and not slow'"
cwd = "../.."
depends-on = "build"
description = "Test with PyTorch on CPU"

[feature.torch-cpu.tasks.test-torch-float32]
cmd = "spin test --no-build -b torch -m 'array_api_backends and not slow'"
env.SCIPY_DEFAULT_DTYPE = "float32"
cwd = "../.."
depends-on = "build"
description = "Test with PyTorch and `SCIPY_DEFAULT_DTYPE=float32` on CPU"

[feature.torch-cuda.dependencies]
pytorch-gpu = "*"

[feature.torch-cuda.tasks.test-torch-cuda]
cmd = "spin test --no-build -b torch -m 'array_api_backends and not slow'"
cwd = "../.."
env.SCIPY_DEVICE = "cuda"
depends-on = "build"
description = "Test with PyTorch on CUDA"


[feature.cupy]
platforms = ["linux-64"]
# XXX: CuPy seems to need cuda13, possibly related to discussion in scipy/scipy#23458
system-requirements = { cuda = "13" }

[feature.cupy.dependencies]
cupy = "*"
cuda-version = "13.*"

[feature.cupy.tasks.test-cupy]
cmd = "spin test --no-build -b cupy -m 'array_api_backends and not slow'"
cwd = "../.."
depends-on = "build"
description = "Test with CuPy"


[feature.jax-cpu]
# include windows so the array-api env can use the jax-cpu feature
platforms = ["linux-64", "osx-arm64", "win-64"]

# Windows support pending: https://github.com/conda-forge/jaxlib-feedstock/issues/161
[feature.jax-cpu.target.unix.dependencies]
jax = "*"
jaxlib = { version = "*", build = "*cpu*" }

# Windows support pending: https://github.com/conda-forge/jaxlib-feedstock/issues/161
[feature.jax-cpu.target.unix.tasks.test-jax]
cmd = "spin test --no-build -b jax.numpy -m 'array_api_backends and not slow'"
cwd = "../.."
depends-on = "build"
description = "Test with JAX on CPU"

[feature.jax-cuda]
platforms = ["linux-64"]

[feature.jax-cuda.dependencies]
# JAX 0.6.2 and 0.7.0 segfault on CUDA
jaxlib = { version = "!=0.6.2,!=0.7.0", build = "cuda12*" }
jax = "*"

[feature.jax-cuda.tasks.test-jax-cuda]
cmd = "spin test --no-build -b jax.numpy -m 'array_api_backends and not slow'"
cwd = "../.."
env.SCIPY_DEVICE = "cuda"
depends-on = "build"
description = "Test with JAX on CUDA"


[feature.array_api_strict]
platforms = ["linux-64", "osx-arm64", "win-64"]

[feature.array_api_strict.dependencies]
array-api-strict = "*"

[feature.array_api_strict.tasks.test-strict]
cmd = "spin test --no-build -b array_api_strict -m 'array_api_backends and not slow'"
cwd = "../.."
depends-on = "build"
description = "Test with array-api-strict"


[feature.dask]
platforms = ["linux-64", "osx-arm64", "win-64"]

[feature.dask.dependencies]
dask-core = "*" # Don't install distributed, tornado, etc.

[feature.dask.tasks.test-dask]
cmd = "spin test --no-build -b dask.array -m 'array_api_backends and not slow'"
cwd = "../.."
depends-on = "build"
description = "Test with Dask"
